### ISSUE TITLE
Add autoprefixer and clean-css

### ISSUE THREAD

**Issue by dmitrykiselyov** [jgonera/autoless#10]
Dziękuję :)
Juliusz, it would be nice if you added [autoprefixer](https://github.com/ai/autoprefixer) and [clean-css](https://github.com/GoalSmashers/clean-css).

Update less to 1.7.0

**Comment by vectart** [comment]
+1

**Comment by jgonera** [comment]
Sorry, this project is no longer maintained. I'm closing the issue before archiving the repository.
