### ISSUE TITLE
Watch module error

### ISSUE THREAD

**Issue by reniowood** [jgonera/autoless#17]
There is a case which causes TypeError in watch module. Here is an error message.

/usr/lib/node_modules/autoless/node_modules/watch/main.js:118
    if (curr.nlink === 0 && (prevFile.file != f || prevFile.action != "removed
            ^
TypeError: Cannot read property 'nlink' of undefined
    at /usr/lib/node_modules/autoless/node_modules/watch/main.js:118:13
    at /usr/lib/node_modules/autoless/node_modules/watch/main.js:81:19
    at Object.oncomplete (fs.js:93:15)

This error does not occurred in version 0.14.0 of watch (it's currently latest version).

**Comment by jgonera** [comment]
What are the steps to reproduce?

**Comment by reniowood** [comment]
As I've inspected, it was reproduced when the watch module detected some change in the vim backup file.

**Comment by jgonera** [comment]
This is still not enough for me to reproduce. It seems like a narrow corner-case anyway. If you feel like preparing a pull request that fixes it, I can review it.
