### ISSUE TITLE
Watching of a single file (and its imports)

### ISSUE THREAD

**Issue by smhg** [jgonera/autoless#23]
I would love to be able to pass one file as the source to autoless:

``` bash
$ autoless source.less destination.css
```

I don't want to watch all files in its directory because I often am only working on one file for the day. I could achieve this by having separate directories, but it would be nice to avoid this.
Would you accept a PR?

**Comment by jgonera** [comment]
Why watching the whole directory is a problem? If you don't change other files, they won't be compiled anyway.

**Comment by smhg** [comment]
Doesn't this have some performance impact?
I have a separate watch task for JS & related files open simultaneously. Altogether that means a lot of files.

What I like a lot about autoless is that it tracks import statements. Which means it really nicely keeps track of dependencies. That's the opposite of watching whole directories for changes.

But if it doesn't have any performance impact, it isn't very important.

**Comment by jgonera** [comment]
It shouldn't have too much impact. `autoless` uses file system events to monitor changes, it doesn't keep polling. I'd say let's worry about performance when we have problems with it.

**Comment by smhg** [comment]
Closing as it should have been closed a long time ago.
