### ISSUE TITLE
'> 1%, last 2 versions' creates a file called '%1' on Windows

### ISSUE THREAD

**Issue by Pomax** [jgonera/autoless#24]
It looks like the CLI isn't taking cross-platform projects into account, generating an actual file `%1` on windows machines (and, presumably, any shell on unix with a scripting component that doesn't support `%<num>` syntax, either). Is there a more cross-platform syntax that can be used here?

**Comment by jgonera** [comment]
Sorry, this project is no longer maintained. I'm closing the issue before archiving the repository.
