### ISSUE TITLE
Keep getting Error: ENOTDIR, scandir 

### ISSUE THREAD

**Issue by EllRod** [jgonera/autoless#26]
Hi, 

I keep getting this error message:
/usr/local/lib/node_modules/autoless/node_modules/watch/main.js:73
    if (err) throw err;
                   ^
Error: ENOTDIR, scandir 'less/style.less'
    at Error (native)

I user following command:
$ autoless less/style.less css/style.css

Any ideas why?

**Comment by giacomocerquone** [comment]
You must give autoless a directory and not a file like you were doing both for input and output.

**Comment by jgonera** [comment]
Sorry, this project is no longer maintained. I'm closing the issue before archiving the repository.
