### ISSUE TITLE
Unclear routing

### ISSUE THREAD

**Issue by ajfarkas** [jgonera/autoless#29]
Setup: compiling from a folder `./less` into the current folder `.`, I found that I have to run
````
$ autoless ./less ..
````

In the hope that I could avoid stringifying all my calcs, I made the mistake of running
````
$ autoless -sm=on ./less ..
````

This watched all of the files in the directory one higher than my current folder, and everything recursively contained within. Which meant I had to force pull all of my repos.

This was, uh, unexpected behavior.

**Comment by jgonera** [comment]
Sorry, this project is no longer maintained. I'm closing the issue before archiving the repository.
