### ISSUE TITLE
Consider archiving the project on Github and depreciating on npm

### ISSUE THREAD

**Issue by frederickjh** [jgonera/autoless#31]
Please consider archiving this project or breathing new life into it.. It has now been six years since a release in April of 2015. A number of commits following that in May 2015 never even got a release to the `npm` package. 
Less has changed in that time and I am finding that there are things that `autoless` does not know about. One example if using the css caluculate() it will do the math inside the parenthesis.
So this:
`left: calc(90% - 109px);` 
becomes 
`left: calc(-19%);`, which is not what we want. Trying to [escape](http://lesscss.org/#escaping) it like this `~"left: calc(90% - 109px);"` results in `autoless` returning the error:

> ParseError: Unrecognised input in less/style.less on line 1055, column 5:

Six years is a small eternity for a web technology project to sit without any updates. If you have moved on then move on an archive it. It will send a warning to people like me that this project could contain dated technology and may not be what I want. I normally first check the last commit date on a project before installing but some how that got missed this time. Also consider adding a warning of some time to the npm package that it is out date to.

**Comment by frederickjh** [comment]
Something like what [RECESS](https://github.com/twitter/recess) has done.

**Comment by jgonera** [comment]
Closing the issue before archiving the repository.
