### ISSUE TITLE
Problem with @imported files from another (non-watched) directory

### ISSUE THREAD

**Issue by AJB99** [jgonera/autoless#9]
Hi there, thanks for autoless, it's fantastic. I'm running into an issue though when I try to watch a file that @imports other files from other directories. Like so:

```
MyProject
   Styles
      main.less
   OtherStyles
      other.less
      other2.less
      other3.less
```

So I've got my main.less file, which @imports all the other.less files like so:

```
@import "../OtherStyles/other.less";
@import "../OtherStyles/other2.less";
@import "../OtherStyles/other3.less";
```

But it's not catching the updates to the 'other' files and/or recompiling my main.less file. There's no error, it just doesn't update main.less.

I'm assuming this may be something to do with the fact that they're outside the directory being watched but I'm really not sure to telll you the truth.

Any help?

Thanks!

**Comment by michalstocki** [comment]
I have a very similar issue. I have some styles installed in `node_modules` as a local link (`npm link`), and updates in these files are not caught.

**Comment by jgonera** [comment]
Sorry, this project is no longer maintained. I'm closing the issue before archiving the repository.
